export enum QueryKeys {
	"PROJECT",
	"PROJECT.STATISTICS",
	"INVITE.LINK",
	"DEPOSIT",
	"STATISTICS",
	"STATISTICS.HOURLY",
	"STATISTICS.COUNTER",
	"TAGS",
	"JOINS",
	"USER.BY.ID",
	"PERSIST.TIMEZONE",
}
